### ISSUE TITLE
Lines appearing on screen

### ISSUE THREAD

**Issue by silverace71** [Redi2Go/PhotonicEngine#2]
![image](https://github.com/Redi2Go/PhotonicEngine/assets/77552030/79ce91da-e8f0-4729-b7f0-c4e002912a7d)

Im not seeing any errors or warning in the logs so I guess its just a problem in... something.

**Comment by Redi2Go** [comment]
Thank you for reaching out! This is a timing issue on Nvidia GPUs that is not present on AMD GPUs, effecting nearly all Nvidia users. I plan on releasing a patch today.

Since it's a known issue this is fine, but for the next time: please attach logs and tell me about your system configuration (GPU, CPU, GPU Driver version)

Thanks, Redi

**Comment by Redi2Go** [comment]
@silverace71 Should be fixed by the new release. Looking forward to your feedback.

**Comment by Redi2Go** [comment]
After testing with GTX 750 and RTX 2070, this seems to be fixed. Closing this issue.
