### ISSUE TITLE
[BUG] POM doesnt work

### ISSUE THREAD

**Issue by TH3N3WN00B** [Redi2Go/PhotonicEngine#29]
Hello, as the title says, POM (Parallax Occlusion Mapping) and reflections from texturepacks are not working and blocks dont have the vanilla ''conected textures''

Vanilla with Photonic:
![2024-07-09_19 49 06](https://github.com/Redi2Go/PhotonicEngine/assets/10799738/9c6e4866-661c-49f7-b9e9-835ca42387ae)

And with Stratum Resourcepack:
![2024-07-09_19 51 19](https://github.com/Redi2Go/PhotonicEngine/assets/10799738/9aebd7cb-736d-4343-8a32-c27b269de697)

**Comment by TH3N3WN00B** [comment]
Also not related to this but love that enchanted things glow purple, dont remove it lol

**Comment by Redi2Go** [comment]
Photonic doesn't work with polygonal meshes and textures, so techniques like Parallax Occlusion and Connected Textures don't really work. 

The seams you can see on the tree, is because the actual block model that is raytraced, is being automatically converted from all the polygonal block models that Minecraft uses. I will have to manually create those block models, so that they don't look so bad.

I am planning on adding reflections to block models, though.

Hope that clears things up
