### ISSUE TITLE
Bad compatibility

### ISSUE THREAD

**Issue by frosthuuund** [Redi2Go/PhotonicEngine#3]
Black terrain.
Broken render at multiple things.
Water looks like pixel mesh.
Mod render fake terrain from previous world if you change render distance and leave to a new world.

**Comment by Redi2Go** [comment]
Please provide more information: Hardware used, OS, Driver version, Mod version, Minecraft version, Resourcepack used, Screenshots.

**Comment by frosthuuund** [comment]
4090, win11,  551.86, bugfix version, 1.20.6, vanilla texture pack, custom awesome skybox
![image](https://github.com/Redi2Go/PhotonicEngine/assets/168279382/954545b0-695f-4da2-9186-925242b3975d)

**Comment by frosthuuund** [comment]
![image](https://github.com/Redi2Go/PhotonicEngine/assets/168279382/e81b213f-8795-47ad-a2db-d5c477bf45d5)

**Comment by frosthuuund** [comment]
flickering mobs (sometimes they render sometimes don't), no lava rendering also sometimes.

**Comment by Redi2Go** [comment]
Any errors in the logs?

https://minecrafthopper.net/help/guides/getting-minecraft-launcher-log/

**Comment by frosthuuund** [comment]
https://paste.nolog.cz/?a3d8da4c55f9e85b#8WbSWY3VSdZqSbShAk8tpA98AN3jVDhx4D6u1D8dN38Y

**Comment by Redi2Go** [comment]
Please check out the new release, should sort out some of your issues.

**Comment by frosthuuund** [comment]
https://litter.catbox.moe/kaeu88.mp4
ignore the possible audio desync
and also this video was encoded in av1

**Comment by Redi2Go** [comment]
Spend some more time coming up with fixes for those issues that you have helpfully reported:
- Render distance of blocks are hard-limited to 8 chunks (because of memory constraints), water is now limited, too (so it doesn't look that bad)
- Error message of "No FabricSkyBoxes compatible resource pack loaded" adjusted to only show when it, indeed, can't load a compatible resource pack.
- I've also added a hint in chat when first logging in, that tells you that Multi-Threading can be enabled in the mod settings menu resulting in much faster loading times.
- Lava is fixed (uses vanilla rendering)
- Invisible entities should now be visible (this was a rough one since I had great trouble reproducing that bug)

Thanks for reporting those issues, I hope I can release a new version in the following hours.

**Comment by frosthuuund** [comment]
After update the render breaks even more...

Alright, list of bugs for today:
Where is the sun?
Where is the biome colors?
Where is texturepack support?
Water surface mirrors all things that lies underwater (after 0.1.2).
I like water from 0.1.1 more, its purple too much rn.
Water fog is not present, but its affecting underwater entities.
Mobs are rendering with the constant level of light, i can spot them in complete darkness.
Will you support semitranslucent blocks?
Are the engine aware of light diffusing?
Lava is not casting light.
Sculk sensor casting the light independently of its state.
Alt tab doing funny things with shadows.
The shadow casts itself from what?  
NVIDIA DSR cause world lighting to pulse if you stay in a dark place enough, cave entrance for example.

Finally, the view bobbing and nausea effects breaks water and mob rendering.

No comments:
![image](https://github.com/Redi2Go/PhotonicEngine/assets/168279382/1e4d0b0b-026f-4ae9-89b9-b74ba9370b5a)

Your mod wasted my left space with the logs:
![image](https://github.com/Redi2Go/PhotonicEngine/assets/168279382/bea44463-ed97-4c21-8f02-96cb0ecdb787)

![image](https://github.com/Redi2Go/PhotonicEngine/assets/168279382/b73c98c7-6a2c-402d-9002-980c9b3184a7)
